# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr = arr*2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

16

In [5]:
#Get values in a range
arr[1:5]

array([2, 4, 6, 8])

In [6]:
#Get values in a range
arr[-4:]

array([14, 16, 18, 20])

In [8]:
#Get values in a range
arr[:5]

array([0, 2, 4, 6, 8])

In [9]:
arr[0:]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr[1:3]

array([2, 4])

In [11]:
arr[1:-1]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr[::2]

array([ 0,  4,  8, 12, 16, 20])

## Broadcasting

<img src="https://cloudxlab.com/blog/wp-content/uploads/2017/12/Screen-Shot-2017-12-13-at-5.57.21-PM.png">

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [13]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

---
**Let's try the same method on Python List**

In [17]:
ar1 = [1,2,3,4,5]
ar1

[1, 2, 3, 4, 5]

In [18]:
ar1[0:2]=100

TypeError: ignored

In [19]:
ar1.mean()

AttributeError: ignored

---
**Back to NumPy Array**

In [20]:
arr.mean()

53.63636363636363

In [21]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [27]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format are: 
- **arr_2d[row][col]** or 
- **arr_2d[row,col]**.

I recommend usually using the comma notation for clarity.

Similar with Python List, array index also start from 0

In [38]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [40]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [41]:
# Getting individual element value
arr_2d[1,0]

20

In [42]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [34]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr>4

In [46]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [49]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])